# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQZyFch9ZNjDAbqlmOvj-UD5HWFTytTi
"""

!pip install numpy

#criando um array
import numpy as np
a=np.array([1,2,3,4,5])
media=np.mean(a)
print(media)

#array com zeros
zero=np.zeros(shape=(4,4,3))
print(zero)

#array com 1
um=np.ones(shape=(2,5,3))
print(um)

#arrange: montar uma determinada sequencia
import numpy as np
p=np.arange(50,200,10)
print(p)