# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUvShltLvNHmo1-9AgW3Bje4nVU3zz4L
"""

!pip install numpy
import numpy as np
temperaturas=np.array([22.1,23.4,21.0,25.5,24.3,26.2,27.0])
print('temperaturas da semana:',temperaturas)
media=temperaturas.mean()
tem_max=temperaturas.max()
tem_min=temperaturas.min()
print('temperatura média da semana:',media)
print('temperatura máxima da semana:',tem_max)
print('temperatura mínima da semana:',tem_min)

temperatura_quarta=temperaturas[3]
print(f' a temperatura na quarta-feira foi: {temperatura_quarta}°C')
temeraturas_fim_de_semana=temperaturas[-2:]
print(f' as temperaturas do fim de semana foram {temeraturas_fim_de_semana}')



arquivo_csv='/content/Temperatura.csv'
temperaturas=np.genfromtxt(arquivo_csv,delimiter=',',skip_header=1)
print('Dados carregados:', temperaturas)
media_temperaturas=np.mean(temperaturas)
print(f'Média de temperaturas:{media_temperaturas:.2f}°C')
max_temperatura=np.max(temperaturas)
print(f'Temperatura máxima:{max_temperatura:.2f}°C')
min_temperatura=np.min(temperaturas)
print(f'Temperatura mínima:{min_temperatura:.2f}°C')

import matplotlib.pyplot as plt
#temperaturas=np.array([22.1,23.4,21.0,25.5,24.3,26.2,27.0]
plt.plot(temperaturas+2, marker="o", linestyle='-', color='b') #'o' e o marcador de círculo, '-' linha sólida e 'b' é a cor azul
plt.plot(temperaturas,marker='o', linestyle='-', color='r')
plt.title('Temperatura Média Diária') #título do gráfico
plt.xlabel('Dia') #rótulo do eixo x
plt.ylabel('Temperatura (°C)') #rótulo do eixo y
plt.grid(True) #adiciona grade ao gráfico para melhorar a leitura
plt.show()

vetor=[1,2,3,4]
for ponteiro in vetor:
  print(ponteiro)

vetor=[1,2,3,4]
for ponteiro in range(len(vetor)):
  print(vetor[ponteiro])

vetor_a=[]
vetor_a=vetor[1:3]
print(vetor_a)
maior=max(vetor)
print(maior)
soma=sum(vetor)
print(soma)
#pegou da posição 1 ao 3

vetor_novo=[]
vetor_novo=vetor_novo.append(1)
print(vetor_novo)