# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPLizQSxrrroTbmTU9FinK_We0XrNyhT
"""



!pip install pandas

#dataframe

import pandas as pd

venda={ 'data_lançamento': [2009,2010,2012, 2021],
       'classificação': [10, 12, 16, 18],
        'gênero': ['terror', 'comédia', 'romance', 'suspense'],
        'quantidade': [10, 3, 6, 20],
        'nota': [5, 6, 10, 9]}

vendas_df= pd.DataFrame(venda)
display(vendas_df)

# importar uma base de dados externa
vendas_df=pd.read_excel("Vendas.xlsx")
display(vendas_df)

#mostrar as primeiras linhas
import pandas as pd
display(vendas_df.head(10))

# importar uma base de dados externa
vendas_df=pd.read_excel("Vendas.xlsx")
display(vendas_df)

#mostrar as primeiras linhas
import pandas as pd
display(vendas_df.head(10))

#descrição da tabela
display(vendas_df.describe())

#editar itens da tabela
produtos=vendas_df['Produto']
display(produtos)

#pegar uma coluna e lugar especifico
vendas_df['ID Loja']== 'Norte Shopping'
display(vendas_df.loc[vendas_df['ID Loja']== 'Norte Shopping'])

#deletar linhas e colunas vazias
vendas_df=vendas_df.dropna(how='all', axis=1)
display(vendas_df)

#somar
transacoes_loja=vendas_df['ID Loja'].value_counts()
display(transacoes_loja)

#agrupar as colunas numericas
faturamento_produto=vendas_df[['Produto', 'Valor Final']].groupby('Produto').sum()
display(faturamento_produto)